enum PendulumEnum {
    TEXTURES = 0,
    MODEL,
    RENDER_PASS_CORE,
    OBJECT_LAYOUTS,
    GRAPHIC_PIPELINE_LAYOUTS,
    GRAPHIC_PIPELINE,
    PENDULUM_DATA,
    ENTITY,
    SCREEN_DATA,
    COMMAND_QUEUE,

    TEXTURES_COLOR = 0,

    MODEL_SPHERE = 0,
    MODEL_LINE,
    MODEL_FONT,

    RENDER_PASS_CLEAN = 0,
    RENDER_PASS_STAY,

    OBJECT_LAYOUT_OBJ = 0,
    OBJECT_LAYOUT_GLTF,
    OBJECT_LAYOUT_FONT,
    OBJECT_LAYOUT_CAMERA,

    GRAPHIC_PIPELINE_LAYOUT_OBJ = 0,
    GRAPHIC_PIPELINE_LAYOUT_GLTF,
    GRAPHIC_PIPELINE_LAYOUT_FONT,

    GRAPHIC_PIPELINE_OBJ = 0,
    GRAPHIC_PIPELINE_GLTF,
    GRAPHIC_PIPELINE_FONT,

    ENTITY_NODE = 0,
    ENTITY_LINE,
    ENTITY_NAME,

    SCREEN_MODEL = 0,
    SCREEN_TEXT,

    COMMAND_QUEUE_GRAPHICS = 0,
};
